# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cyber3330d/Downloads/es501/es501/default.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 860)
        Form.setMinimumSize(QtCore.QSize(800, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/l/compeng_Logo_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("\n"
"background-color:#f6fcff;\n"
"color:#002060;\n"
"border:none;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_layout = QtWidgets.QVBoxLayout()
        self.header_layout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.header_layout.setSpacing(0)
        self.header_layout.setObjectName("header_layout")
        self.logo = QtWidgets.QLabel(Form)
        self.logo.setMinimumSize(QtCore.QSize(400, 0))
        self.logo.setStyleSheet("image: url(:/assets/compeng_Logo.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.header_layout.addWidget(self.logo)
        self.welcome_text = QtWidgets.QLabel(Form)
        self.welcome_text.setStyleSheet("font-size:24px;\n"
"font-weight:800;\n"
"color:#002060;\n"
"margin:0 auto;")
        self.welcome_text.setObjectName("welcome_text")
        self.header_layout.addWidget(self.welcome_text)
        self.header_layout.setStretch(0, 1)
        self.header_layout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.header_layout)
        self.slideshow = QtWidgets.QLabel(Form)
        self.slideshow.setMinimumSize(QtCore.QSize(0, 0))
        self.slideshow.setStyleSheet("image: url(:/assets/slideshow_images_folder/image 3.png);")
        self.slideshow.setText("")
        self.slideshow.setScaledContents(True)
        self.slideshow.setObjectName("slideshow")
        self.verticalLayout.addWidget(self.slideshow)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Compeng Receptionist AI"))
        self.welcome_text.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">WELCOME TO THE DEPARTMENT OF <br/>COMPUTER ENGINEERING</span></p></body></html>"))
import assets_rc
